CONFIG = {
    "device_id": "edge-jetson-01",
    "schema_version": "hifive.edge.v1",
    "plate_class_id": 0,
    "transport": {
        "kind": "webtransport_ingress",
        "ingress_host": "10.0.0.10",
        "ingress_port": 4433,
        "webtransport_path": "/hifive/edge",
        "server_name": "hifive-ingress.internal",
        "verify_tls": False,
        "timeout_sec": 0.3,
        "retry_enabled": True,
        "retry_initial_sec": 0.2,
        "retry_max_sec": 1.0,
        "retry_max_items_per_cycle": 16,
        "failover_enabled": False,
        "standby_ingress_host": "",
        "standby_ingress_port": 4433,
        "standby_server_name": "",
        "standby_verify_tls": False,
        "failover_recheck_sec": 0.5,
        "dry_run": False,
    },
    "spool_dir": "/home/jetson/hifive/spool",
    "yolo": {
        "engine_path": "/home/jetson/hifive/models/yolo11s_fp16.engine",
        "precision": "fp16",
        "input_width": 960,
        "input_height": 960,
        "confidence_threshold": 0.25,
        "nms_iou_threshold": 0.45,
    },
    "ocr": {
        "engine_path": "/home/jetson/hifive/engines/ocr_plate_fp16.engine",
        "precision": "fp16",
        "input_width": 160,
        "input_height": 48,
        "vocab_path": "/home/jetson/hifive/models/ocr_metadata.json",
        "confidence_threshold": 0.70,
        "min_crop_width": 100,
        "min_crop_height": 32,
    },
    "cameras": [
        {
            "source_id": 0,
            "camera_id": "cam-rear-01",
            "camera_group_id": "gate-a-pair-01",
            "camera_role": "rear",
            "direction": "rear",
            "source_uri": "file:///home/jetson/hifive/videos/rear_demo.mp4",
            "source_pipeline": "",
            "frame_width": 1920,
            "frame_height": 1080,
            "crop_rect": {"x": 480, "y": 60, "w": 960, "h": 960},
            "yolo_input_slots": [
                {
                    "lane_no": 1,
                    "global_lane_no": 1,
                    "source_rect": {"x": 0, "y": 540, "w": 960, "h": 480},
                    "canvas_rect": {"x": 0, "y": 0, "w": 960, "h": 480},
                },
                {
                    "lane_no": 2,
                    "global_lane_no": 2,
                    "source_rect": {"x": 960, "y": 540, "w": 960, "h": 480},
                    "canvas_rect": {"x": 0, "y": 480, "w": 960, "h": 480},
                },
            ],
            "lane_regions": [
                {
                    "lane_no": 1,
                    "global_lane_no": 1,
                    "polygon": [[0, 0], [960, 0], [960, 1080], [0, 1080]],
                    "crossing_line": [[0, 720], [960, 720]],
                },
                {
                    "lane_no": 2,
                    "global_lane_no": 2,
                    "polygon": [[960, 0], [1920, 0], [1920, 1080], [960, 1080]],
                    "crossing_line": [[960, 720], [1920, 720]],
                },
            ],
        },
        {
            "source_id": 1,
            "camera_id": "cam-front-01",
            "camera_group_id": "gate-a-pair-01",
            "camera_role": "front",
            "direction": "front",
            "source_uri": "file:///home/jetson/hifive/videos/front_demo.mp4",
            "source_pipeline": "",
            "frame_width": 1920,
            "frame_height": 1080,
            "crop_rect": {"x": 480, "y": 60, "w": 960, "h": 960},
            "yolo_input_slots": [
                {
                    "lane_no": 1,
                    "global_lane_no": 1,
                    "source_rect": {"x": 0, "y": 540, "w": 960, "h": 480},
                    "canvas_rect": {"x": 0, "y": 0, "w": 960, "h": 480},
                },
                {
                    "lane_no": 2,
                    "global_lane_no": 2,
                    "source_rect": {"x": 960, "y": 540, "w": 960, "h": 480},
                    "canvas_rect": {"x": 0, "y": 480, "w": 960, "h": 480},
                },
            ],
            "lane_regions": [
                {
                    "lane_no": 1,
                    "global_lane_no": 1,
                    "polygon": [[0, 0], [960, 0], [960, 1080], [0, 1080]],
                    "crossing_line": [[0, 720], [960, 720]],
                },
                {
                    "lane_no": 2,
                    "global_lane_no": 2,
                    "polygon": [[960, 0], [1920, 0], [1920, 1080], [960, 1080]],
                    "crossing_line": [[960, 720], [1920, 720]],
                },
            ],
        },
    ],
}
