# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tolling_pb2 as tolling__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tolling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TollingEventServiceStub(object):
    """=====================================================================
    hifive - Edge(FastAPI)  ->  Backend(Spring Boot) 전송 계약 정의
    모든 통과 이벤트는 Protobuf 바이너리로 직렬화되어 gRPC로 전송된다.
    JSON 대비 페이로드 크기 60~80% 절감, 파싱 비용 감소가 목표.
    =====================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPassageEvent = channel.unary_unary(
                '/hifive.tolling.v1.TollingEventService/SendPassageEvent',
                request_serializer=tolling__pb2.PassageEventRequest.SerializeToString,
                response_deserializer=tolling__pb2.PassageEventResponse.FromString,
                _registered_method=True)
        self.StreamPassageEvents = channel.stream_stream(
                '/hifive.tolling.v1.TollingEventService/StreamPassageEvents',
                request_serializer=tolling__pb2.PassageEventRequest.SerializeToString,
                response_deserializer=tolling__pb2.PassageEventResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/hifive.tolling.v1.TollingEventService/Heartbeat',
                request_serializer=tolling__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=tolling__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class TollingEventServiceServicer(object):
    """=====================================================================
    hifive - Edge(FastAPI)  ->  Backend(Spring Boot) 전송 계약 정의
    모든 통과 이벤트는 Protobuf 바이너리로 직렬화되어 gRPC로 전송된다.
    JSON 대비 페이로드 크기 60~80% 절감, 파싱 비용 감소가 목표.
    =====================================================================

    """

    def SendPassageEvent(self, request, context):
        """단건 통과 이벤트 전송 (저신뢰도/검수 케이스, 보정 재전송용)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPassageEvents(self, request_iterator, context):
        """실시간 통과 이벤트 양방향 스트리밍 (정상 운영 채널)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """엣지 노드 헬스체크 (백엔드가 엣지 상태를 추적)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TollingEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPassageEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPassageEvent,
                    request_deserializer=tolling__pb2.PassageEventRequest.FromString,
                    response_serializer=tolling__pb2.PassageEventResponse.SerializeToString,
            ),
            'StreamPassageEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPassageEvents,
                    request_deserializer=tolling__pb2.PassageEventRequest.FromString,
                    response_serializer=tolling__pb2.PassageEventResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=tolling__pb2.HeartbeatRequest.FromString,
                    response_serializer=tolling__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hifive.tolling.v1.TollingEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hifive.tolling.v1.TollingEventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TollingEventService(object):
    """=====================================================================
    hifive - Edge(FastAPI)  ->  Backend(Spring Boot) 전송 계약 정의
    모든 통과 이벤트는 Protobuf 바이너리로 직렬화되어 gRPC로 전송된다.
    JSON 대비 페이로드 크기 60~80% 절감, 파싱 비용 감소가 목표.
    =====================================================================

    """

    @staticmethod
    def SendPassageEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hifive.tolling.v1.TollingEventService/SendPassageEvent',
            tolling__pb2.PassageEventRequest.SerializeToString,
            tolling__pb2.PassageEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPassageEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hifive.tolling.v1.TollingEventService/StreamPassageEvents',
            tolling__pb2.PassageEventRequest.SerializeToString,
            tolling__pb2.PassageEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hifive.tolling.v1.TollingEventService/Heartbeat',
            tolling__pb2.HeartbeatRequest.SerializeToString,
            tolling__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
