server:
  address: 0.0.0.0
  port: 8585

spring:
  datasource:
    url: ${HIFIVE_DB_URL:jdbc:postgresql://localhost:5433/hifive}
    username: ${HIFIVE_DB_USERNAME:pgadmin}
    password: ${HIFIVE_DB_PASSWORD:1004}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

hifive:
  ingress-video:
    base-url: ${HIFIVE_INGRESS_VIDEO_BASE_URL:http://127.0.0.1:8000}
    status-path: ${HIFIVE_INGRESS_VIDEO_STATUS_PATH:/video/status}
    stream-path: ${HIFIVE_INGRESS_VIDEO_STREAM_PATH:/video/stream.mjpg}
<<<<<<< HEAD
    hls-playlist-path: ${HIFIVE_INGRESS_VIDEO_HLS_PLAYLIST_PATH:/video/hls/master.m3u8}
    hls-segment-base-path: ${HIFIVE_INGRESS_VIDEO_HLS_SEGMENT_BASE_PATH:/video/hls/}
    connect-timeout-ms: ${HIFIVE_INGRESS_VIDEO_CONNECT_TIMEOUT_MS:1000}
    read-timeout-ms: ${HIFIVE_INGRESS_VIDEO_READ_TIMEOUT_MS:0}
=======
    connect-timeout-ms: ${HIFIVE_INGRESS_VIDEO_CONNECT_TIMEOUT_MS:1000}
    read-timeout-ms: ${HIFIVE_INGRESS_VIDEO_READ_TIMEOUT_MS:3000}
>>>>>>> 7079a4460c30b6df7d5d303fd0835c75520e4038
